### ISSUE TITLE
feature request : only retry for certain types of exception

### ISSUE THREAD

**Issue by thomasleveil** [kaelzhang/python-aioretry#2]
It would be very useful to pass the exception as a second parameter of the retry policy function. 
This way, the retry policy function could decide if we need to retry or fail depending on exception type (or anything else related to the exception)

**Comment by kaelzhang** [comment]
Good proposal. Looking into this.

**Comment by kaelzhang** [comment]
Landed in `2.1.0`

See https://github.com/kaelzhang/python-aioretry#only-retry-for-certain-types-of-exceptions

**Comment by thomasleveil** [comment]
That was quick ! Thank you

**Comment by kaelzhang** [comment]
You are right that providing the exception as the second parameter of the retry policy function is a better solution. That we could even provide different delay for different exception types.

**Comment by kaelzhang** [comment]
To avoid introducing more parameters in the future, I've changed the design of `retry_policy`.

Now `retry_policy` and `before_retry` have the same parameter of type `RetryInfo`

```py
from aioretry import (
  RetryPolicyStrategy,
  RetryInfo
)

def retry_policy(info: RetryInfo) -> RetryPolicyStrategy:
  info.fails
  info.exception
  info.since  # the first time when failure occurs
  return True, 0
```

It is recommended to upgrade to `5.0.0`

FYI @thomasleveil
