### ISSUE TITLE
Consider using Coroutine instead of Awaitable

### ISSUE THREAD

**Issue by ic-it** [kaelzhang/python-aioretry#6]
Pycharm makes warnings like `Expected type 'Generator[Any, None, Any] | Coroutine' (matched generic type 'Generator[Any, None, _T] | Coroutine[Any, Any, _T]'), got 'Awaitable' instead`.
I would like to suggest that you use Coroutine instead of Awaitable

**Comment by kaelzhang** [comment]
Sorry I don't use Pycharm.

Is the purpose to make the typing more generic?

**Comment by ic-it** [comment]
Yes, it is. I purpose to create more generic types.  
I'm not an expert in Python's type world, but I can try to contribute and add this feat to the library.  
Off-topic: what do you think about async-iterators support?
